### ISSUE TITLE
Header and Footer not coming in Modern Pages

### ISSUE THREAD

**Issue by bhanuchintha** [dannyjessee/SPFxHeaderFooter#1]
Hello Danny,

Thanks for the detailed post and very happy to see that the Custom navigation & script is available in modern site.

I have tried this approach. But, I see that the header and footer are visible in the Class pages & not in the modern pages. I have also disabled the NoScript property of the site. Can you please help me here - what might have went wrong.

Please find the attached images of this issue - 

![modern site 1](https://user-images.githubusercontent.com/19674673/34307240-138c5220-e76d-11e7-9d47-7daab8f5da73.PNG)
![apps installed](https://user-images.githubusercontent.com/19674673/34307275-3a667a60-e76d-11e7-9e73-d7a0cc430310.PNG)
![classic library](https://user-images.githubusercontent.com/19674673/34307276-3a9e8e78-e76d-11e7-9efc-df69b09e1d73.PNG)
![modern library](https://user-images.githubusercontent.com/19674673/34307277-3ac9a5fe-e76d-11e7-9562-d8bf24cdacf7.PNG)

Thanks & Regards,
Bhanu

**Comment by dannyjessee** [comment]
Did you update write-manifests.json to reflect the location where you copied the assets from temp/deploy when you built the package?
