### ISSUE TITLE
Does this solution work with Sharepoint server 2019 on-prem

### ISSUE THREAD

**Issue by F1ackmonkey** [dannyjessee/SPFxHeaderFooter#2]
I realize this solution is 6 years old but I have a need for something similar with Sharepoint server 2019 on-prem.  Will this work?  I am new to the SPFx and I don't yet understand how this works.

**Comment by dannyjessee** [comment]
I've been away from SPFx development for awhile now, so I have not personally tested this against an on-prem SharePoint Server 2019 installation, but it should work as SPFx 1.4.1 is supported per [Microsoft documentation](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-and-subscription-edition-support). You may need to upgrade this solution to work with the SPFx 1.4.1 generator. Best of luck to you!
